server:
  port: 7000
  servlet:
    context-path: /demo-business

spring:
  application:
    name: eureka-client-demo-business
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://59.110.229.83:3306/ad_data?autoReconnect=true
    username: root
    password: yuzhuang1995!
    tomcat:
      max-active: 4
      min-idle: 2
      initial-size: 2

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/


