server:
  port: 9000
spring:
  application:
    name: demo-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/

zuul:
  prefix: /aiqinhai
  routes:
    demo-business:
      path: /demo-business/**
      serviceId: eureka-client-demo-business
      strip-prefix: false
#    search:
#      path: /ad-search/**
#      serviceId: eureka-client-ad-search
#      strip-prefix: false
